import os
import re

def clean_text(text):
    """
    Cleans up input clinical text by normalizing multiple spaces and lines
    into single whitespace, and stripping leading/trailing whitespace.
    """
    if not text:
        return ""
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def parse_pubtator_file(filepath):
    """
    Parses a PubTator file format to extract article text,
    labeled entities, and ICD-10/MeSH codes.
    
    Expected format:
    PMID|t|TitleText
    PMID|a|AbstractText
    PMID    StartOffset    EndOffset    EntityText    EntityType    Identifier
    
    Returns a list of dictionaries with structure:
    {
        "text": full_text,
        "entities": [{"entity": ..., "type": ..., "start": ..., "end": ...}],
        "icd10": [list of identifiers/codes]
    }
    """
    parsed_data = []
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Target PubTator file not found at: {filepath}")

    with open(filepath, 'r', encoding='utf-8') as f:
        # Split by double newline to isolate individual articles/documents
        articles = f.read().strip().split('\n\n')

    for article in articles:
        lines = article.split('\n')
        if not lines or len(lines) < 2:
            continue

        try:
            # First line is the title: PMID|t|TitleText
            title = lines[0].split('|t|')[1]
            # Second line is the abstract: PMID|a|AbstractText
            abstract = lines[1].split('|a|')[1]
            full_text = title + " " + abstract

            entities = []
            icd_codes = []

            # Remaining lines represent entity annotations
            for line in lines[2:]:
                parts = line.split('\t')
                if len(parts) == 6:
                    entities.append({
                        "entity": parts[3],
                        "type": parts[4],
                        "start": int(parts[1]),
                        "end": int(parts[2])
                    })
                    icd_codes.append(parts[5])

            parsed_data.append({
                "text": full_text,
                "entities": entities,
                # Store unique diagnosis/MeSH/ICD codes
                "icd10": list(set(icd_codes))
            })
        except IndexError:
            # Skip malformed lines or paragraphs
            continue
    return parsed_data

def process_blurb_bc2gm(df):
    """
    Processes a BLURB/BC2GM dataset DataFrame. Reconstructs text and extracts
    character-level entity locations from list of tokens and labels.
    
    Returns a list of dictionaries in standard format:
    {
        "text": full_text,
        "entities": [{"entity": ..., "type": ..., "start": ..., "end": ...}],
        "icd10": []
    }
    """
    processed = []
    # BC2GM tag IDs: 0 -> O, 1 -> B-Gene, 2 -> I-Gene
    blurb_tags = {0: "O", 1: "B-Gene", 2: "I-Gene"}

    for _, row in df.iterrows():
        tokens = row['tokens']
        ner_tags = row['ner_tags']
        
        text_parts = []
        entities = []
        curr_char = 0
        current_ent = None
        
        for tok, tag_id in zip(tokens, ner_tags):
            tag = blurb_tags.get(tag_id, "O")
            start = curr_char
            end = curr_char + len(tok)
            
            text_parts.append(tok)
            # Reconstruct positions assuming tokens are space-separated
            curr_char = end + 1  
            
            if tag.startswith("B-"):
                if current_ent:
                    entities.append(current_ent)
                current_ent = {
                    "entity": tok,
                    "type": "Gene",
                    "start": start,
                    "end": end
                }
            elif tag.startswith("I-") and current_ent:
                current_ent["entity"] += " " + tok
                current_ent["end"] = end
            else:
                if current_ent:
                    entities.append(current_ent)
                    current_ent = None
        if current_ent:
            entities.append(current_ent)
            
        full_text = " ".join(tokens)
        processed.append({
            "text": full_text,
            "entities": entities,
            "icd10": []
        })
    return processed

def align_tokens_and_tags(text, entities, tokenizer, tag_to_ix, max_len=512):
    """
    Aligns character-level entity annotations with subword tokens generated by a tokenizer.
    Ensures that when a word is split, the first subword gets B-<Type> and subsequent
    subwords get I-<Type> or -100 masking value.
    
    Returns:
        input_ids: List of token IDs
        attention_mask: List of 0s and 1s representing attention masks
        labels: List of label indices corresponding to tag_to_ix, or -100 for ignored tokens
    """
    # Get offsets to map tokens back to original character positions
    encoded = tokenizer(
        text, 
        return_offsets_mapping=True, 
        add_special_tokens=True, 
        truncation=True, 
        max_length=max_len
    )
    input_ids = encoded["input_ids"]
    attention_mask = encoded["attention_mask"]
    offsets = encoded["offset_mapping"]

    # Initialize all tags to "O" (outside)
    labels = [tag_to_ix["O"]] * len(input_ids)

    for ent in entities:
        start_char, end_char = ent["start"], ent["end"]
        ent_type = ent["type"]
        b_tag = f"B-{ent_type}"
        i_tag = f"I-{ent_type}"
        
        b_idx = tag_to_ix.get(b_tag, 0)
        i_idx = tag_to_ix.get(i_tag, 0)

        first = True
        for idx, (s, e) in enumerate(offsets):
            # Skip special tokens (like [CLS], [SEP]) where offset is (0, 0)
            if s == e == 0:
                labels[idx] = -100
                continue
                
            # Check if current token falls within the character range of the entity
            if s >= start_char and e <= end_char:
                if first:
                    labels[idx] = b_idx
                    first = False
                else:
                    labels[idx] = i_idx
    return input_ids, attention_mask, labels
